### ISSUE TITLE
Value Error: Passed header names mismatch usecols

### ISSUE THREAD

**Issue by waalkes** [taolonglab/himapdb#1]
I am following your github instructions exactly.  Everything works fine until I get to this step:
Extract 16S sequences from full genomes

I get the following error:
(himapdb) tron:/mnt/disk4/labs/salipante/programs/himapdb/himapdb (master) $ python3 py/extract.py data/bacteria_assembly_summary_2019-07-15.txt data/features/ data/sequences/ data/16s_from_genomes_bacteria_2019-07-15.fasta
Traceback (most recent call last):
  File "py/extract.py", line 203, in <module>
    ass_s_dir=ass_s_dir, fa_out_exist_action=action)
  File "py/extract.py", line 45, in main
    dtype={'# assembly_accession': str, 'ftp_path': str})
  File "/mnt/disk4/labs/salipante/programs/himapdb/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/mnt/disk4/labs/salipante/programs/himapdb/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/mnt/disk4/labs/salipante/programs/himapdb/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/mnt/disk4/labs/salipante/programs/himapdb/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/mnt/disk4/labs/salipante/programs/himapdb/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 882, in pandas._libs.parsers.TextReader._get_header
ValueError: Passed header names mismatches usecols

Any idea what is going on?

Thanks

**Comment by igor25** [comment]
Hi,

I think the error is you're passing `data/bacteria_assembly_summary_2019-07-15.txt` to `extract.py` instead of `data/bacteria_assembly_summary_**filter**_2019-07-15.txt` (this file should be the output of the first step).

I just reproduced all the steps myself with the newest data, so it works for me.

**Comment by waalkes** [comment]
You are correct I screwed up.  Sorry.  working now.

________________________________

**Comment by igor25** [comment]
No problem! Please feel free to post in case you get stuck with anything here.
